language: python
stages:
  - install
  - deploy

jobs:
  include:
    # Test install the package
    - stage: install
      install: pip install -U pip setuptools wheel
      name: "Setup and import test"
      python: "3.6"
      script: 
        - python setup.py install


    # Deploy to PyPi.
    - stage: deploy
      name: "Deploy to PyPi"
      install: pip install -U pip setuptools wheel
      script: skip
      deploy: &pypi
        skip_existing: true
        provider: pypi
        user: "$PYPIUSER"
        password: "$PYPIKEY"
        on:
          tags: true