#!/usr/bin/with-contenv bash
###############################################
#
#  Run NGINX
#
###############################################

s6-svwait -u -t 5000 /var/run/s6/services/store

echo "-----------------------------------------"
echo
echo "Custom Component Store is running on port 8100"
echo
echo "-----------------------------------------"
echo
echo "The port shown in the message below is wrong, use 8100 or a port you specified with '-p'"

exec nginx -g "daemon off;"