#!/usr/bin/with-contenv bash
###############################################
#
#  Run NGINX
#
###############################################

s6-svwait -u -t 5000 /var/run/s6/services/store

echo "-----------------------------------------"
echo
echo "Custom Component Store is running on port 8100"
echo
echo "-----------------------------------------"

exec nginx -g "daemon off;"