#!/usr/bin/with-contenv bash
###############################################
#
#  Run the custom-component-store
#
###############################################

exec redis-server --protected-mode no