#!/usr/bin/with-contenv bash
###############################################
#
#  Run the custom-component-store
#
###############################################

exec python3 -u "/opt/component-store/server.py"